# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # Ecosystem for Python packages
    directory: "/" # Location of package manifests (root directory)
    schedule:
      interval: "daily" # Check for updates daily

  - package-ecosystem: "github-actions" # Ecosystem for GitHub Actions
    directory: "/" # Location of workflows (root directory)
    schedule:
      interval: "daily" # Check for updates daily

  - package-ecosystem: "docker" # Ecosystem for Docker dependencies
    directory: "/" # Location of Dockerfiles (root directory)
    schedule:
      interval: "daily" # Check for updates daily

  - package-ecosystem: "npm" # Ecosystem for JavaScript packages
    directory: "/" # Location of package.json (root directory)
    schedule:
      interval: "daily" # Check for updates daily
