[tool.poetry]
name = "exit"
version = "exit()"
description = ""
authors = ["GaryOcean428 <braden.lang77@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
